# Basic Jekyll configuration for GitHub Pages
title: M Nethmina Perera| Financial Analyst | Data Scientist | Researcher
description: Passionate about financial analytics, statistical modeling, and data-driven decision-making
url: "https://MHMNP2021.github.io" 
baseurl: "" # Since your site is in a project repository

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Custom variables
author: MHMN Perera
email: mhmn200021@gmail.com
github_username: MHMN2021
linkedin_username: MHM N PERERA


# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

