# Basic Jekyll configuration for GitHub Pages
title: M Nethmina Perera| Financial Analyst | Data Scientist | Researcher
description: Passionate about financial analytics, statistical modeling, and data-driven decision-making
url: "" # Add your GitHub Pages URL when available
baseurl: "" # Leave empty if your site is at the root of your domain

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Custom variables
author: MHMN Perera
email: mhmn200021@gmail.com
github_username: MHMN2021
linkedin_username: MHM N PERERA


# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

