# Basic Jekyll configuration for GitHub Pages
title: My Portfolio
description: Personal portfolio website showcasing my projects and skills
url: "" # Add your GitHub Pages URL when available
baseurl: "" # Leave empty if your site is at the root of your domain

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Custom variables
author: Your Name
email: youremail@example.com
github_username: your-github-username

